version: '3'

services:
  db:
    image: postgres:13
    ports:
      - 30000:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./swagger.json:/data/swagger.json
    environment:
      - SWAGGER_JSON=/data/swagger.json
  server:
    depends_on:
      - db
    build:
      context: server
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - LOG_QUERIES=true
  # nginx:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - server
  # frontend:
  #   build:
  #     context: frontend